# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Generate release artifacts

on:
  push:
    branches: [ "releases/v0.*" ]
    tags:
      - v0.*
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Split branch name
        env:
          BRANCH: ${{ github.ref_name }}
        id: version_branch
        run: echo "::set-output name=branch_version::${BRANCH##*/v}" >> $GITHUB_OUTPUT
        
      - name: Get next version
        id: versioning_tag
        uses: reecetech/version-increment@2023.10.1
        with:
          scheme: semver
          increment: patch
          
      - name: Generate versions
        if: ${{startsWith(github.ref_name,'releases/v')}}
        id: versioning_branch
        uses: HardNorth/github-version-generate@v1.4.0
        with:
          version-source: variable
          version: ${{steps.branch_version.outputs.branch_version}}
      - name: Override major version
        if: ${{steps.versioning_tag.outputs.major-version!= steps.versioning_branch.outputs.major-version}}
        id: version_major_override
        run: |
          echo "NEXT_VERSION=${{}}" >> $GITHUB_ENV
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo "Version parsed from tags: ${{steps.versioning_tag.outputs.tag}}
          echo "Semver generated env.CURRENT_VERSION: ${{env.CURRENT_VERSION}}
          echo "Semver generated env.RELEASE_VERSION: ${{env.RELEASE_VERSION}}
          echo "Semver generated env.NEXT_VERSION: ${{env.NEXT_VERSION}}
          echo "Semver generated env.NEXT_RELEASE_VERSION: ${{env.NEXT_RELEASE_VERSION}}
          echo "Semver generated steps.versioning_branch.outputs.minor-version: ${{steps.versioning_branch.outputs.minor-version}}